New Services
coollabsio/coolify pull request #4180
Opened 2024-11-08 10:15 UTC by peaklabs-dev

## Changes
- 

## Issues
- fix #

2024-11-08 20:20 UTC, brrock requested changes
lGTM

2024-11-08 20:20 UTC, brrock approved these changes

2024-11-08 20:20 UTC, brrock approved these changes
LGTM GitHub what going on

2024-11-12 13:46 UTC, andrasbacsai commented
Thank you for the PR!

2024-11-12 13:49 UTC, merged