Feat: New Services
coollabsio/coolify pull request #4209
Opened 2024-11-09 01:00 UTC by librelol

## New Services
- Private Bin
- Redlib

2024-11-09 01:01 UTC, librelol commented
I believed I followed all the contribution rules. Let me know if I missed anything. Thank you.

2024-11-12 12:42 UTC, peaklabs-dev requested changes

2024-11-12 12:42 UTC, peaklabs-dev commented on templates/compose/redlib.yaml
> +    env_file: .env
Remove the `.env` file and add it to the `environment` section.

2024-11-12 12:43 UTC, peaklabs-dev commented
1. Please add logos to your services.
2. Also add healtchecks to both services.
3. Also test them by inserting the compose into the compose deplyo type, because the first one I tried did not really work.

2024-11-13 18:16 UTC, RayBB commented
Sweet I love redlib!

2024-11-13 20:57 UTC, librelol commented
> 1. Please add logos to your services.
> 
>     2. Also add healtchecks to both services.
> 
>     3. Also test them by inserting the compose into the compose deplyo type, because the first one I tried did not really work.

Sure thing man, I had them running on my service actually but I'll follow through with those.

2024-11-13 21:12 UTC, librelol commented
> 1. Please add logos to your services.
> 
>     2. Also add healtchecks to both services.
> 
>     3. Also test them by inserting the compose into the compose deplyo type, because the first one I tried did not really work.

Also redlib on start takes a good couple of minutes to actually start working.

2024-11-13 21:30 UTC, ghost commented on templates/compose/redlib.yaml
> +    env_file: .env
Adjusted that and added the logos.

2024-11-14 20:09 UTC, librelol commented
I've observed that Redlib is pretty unreliable. It will need some more testing.

2024-11-14 20:12 UTC, RayBB commented
It's weird because redlib not running behine coolify works flawlessly. But when it's behind coolify it often times out. If I ssh into the container and curl the service it always responds basically instantly. It makes me think there's something weird about the reverse proxy config. There's a small chance it could be related to the face that redlib doesn't support head requests but idk.

2024-11-14 20:24 UTC, peaklabs-dev commented
I will mark it as draft, when you are done pleas make it ready for review.

2024-11-15 17:13 UTC, librelol commented
> It's weird because redlib not running behine coolify works flawlessly. But when it's behind coolify it often times out. If I ssh into the container and curl the service it always responds basically instantly. It makes me think there's something weird about the reverse proxy config. There's a small chance it could be related to the face that redlib doesn't support head requests but idk.

I don't think so. It just takes a bit to startup. I think it might have to do with something relating to indexing reddit? But apart from that I got it to work without a problem mostly. I will do some more testing in general with the variables to ensure a stable production experience since its pretty unreliable right now.

2024-11-15 17:14 UTC, librelol commented
I ended up changing the default sub reddit to worldnews due to for whatever reason the example option redlib gives for it doesn't actually work.

2024-11-15 22:17 UTC, librelol commented
Alright, Redlib seems to be pretty stable. And I've implemented the proper coolify environment variables. I think it is ready, I also have been running redlib for about 3 hours and it has no problems accessing various sub reddits and the homepage is working well now that it is set to world news.

2024-11-25 12:39 UTC, peaklabs-dev commented
Thanks for the PR, next time please make separate PRs for each service. Also, I will not add Gothub because it is too small a service to officially maintain.

2024-11-25 12:39 UTC, merged