Update postiz.yaml
coollabsio/coolify pull request #4354
Opened 2024-11-21 15:08 UTC by dr-diffie

### Proposed Improvements to Postiz Template

I'd like to propose several improvements to the current Postiz template that enhance security, reliability, and configuration flexibility:

The improved template provides a more production-ready setup while maintaining compatibility with Coolify's requirements. It follows best practices for Docker deployments and provides better security out of the box.

## Changes

#### Security Enhancements
- Added Redis ACL configuration with proper authentication
- Implemented secure health checks with authentication
- Enhanced PostgreSQL security configurations

#### Reliability Improvements
- Added memory limits and resource management for Redis
- Implemented proper data persistence configurations
- Added tmpfs for temporary files
- More comprehensive health check configurations with proper retry/timeout strategies
- Better dependency management with health conditions

#### Configuration Flexibility
- Support for all environment variables from Postiz documentation
- Added Cloudflare R2 integration support
- Logical grouping of environment variables
- Default values for critical settings
- Better volume management with explicit drivers

2024-11-21 18:00 UTC, dr-diffie commented
@peaklabs-dev

2024-11-21 20:12 UTC, peaklabs-dev requested changes

2024-11-21 20:12 UTC, peaklabs-dev commented on templates/compose/postiz.yaml
> +volumes:
This volume section is not necessary as Coolify will auto-generate it.

2024-11-21 20:12 UTC, peaklabs-dev commented on templates/compose/postiz.yaml
> +        - 'redis://${SERVICE_USER_REDIS}:${SERVICE_PASSWORD_REDIS}@localhost:6379'
If you use this you ofc have to keep the environment section for Redis with the username and password (I think you deleted it by accident)

2024-11-21 20:12 UTC, peaklabs-dev commented on templates/compose/postiz.yaml
> +    deploy:
Do not add memory limit to the official template, if you need this for yourself you can add it after the fact.

2024-11-21 20:12 UTC, peaklabs-dev commented on templates/compose/postiz.yaml
> +    image: 'ghcr.io/gitroomhq/postiz-app:latest'
Overall feedback, it is unnecessary to add `'` around images, env variables and so on, just makes it less readable.

2024-11-21 20:12 UTC, peaklabs-dev commented on templates/compose/postiz.yaml
> +      --aclfile /data/users.acl
I think using an acl file is overkill and just makes it harder to maintain. If you want to use this for your own deployment you can ofc do it like this.

2024-11-21 22:37 UTC, dr-diffie commented on templates/compose/postiz.yaml
> +    image: 'ghcr.io/gitroomhq/postiz-app:latest'
Agreed! Removed.

2024-11-21 22:39 UTC, dr-diffie commented on templates/compose/postiz.yaml
> +      --aclfile /data/users.acl
✅ Simplified: Removed ACL configuration in favor of simple password authentication, which provides sufficient security while being easier to maintain.

2024-11-21 22:40 UTC, dr-diffie commented on templates/compose/postiz.yaml
> +        - 'redis://${SERVICE_USER_REDIS}:${SERVICE_PASSWORD_REDIS}@localhost:6379'
Fixed: Simplified Redis healthcheck to use basic PING with password authentication. Updated the Redis URL to use the 'default' username for better compatibility with the Node.js Redis client. You are right, I indeed deleted it by accident.

2024-11-21 22:41 UTC, dr-diffie commented on templates/compose/postiz.yaml
> +    deploy:
Removed: Eliminated memory limits from the template to maintain flexibility. I am still pretty sure 256 MB is more than enough but happy to use it only in my deployments ☺️

2024-11-21 22:41 UTC, dr-diffie commented on templates/compose/postiz.yaml
> +volumes:
Did not know that! Thanks removed

2024-11-21 22:48 UTC, dr-diffie commented
Done ✅

2024-11-22 21:30 UTC, peaklabs-dev approved these changes

2024-11-22 21:30 UTC, merged