Add Matrix Chat as Service With Element WebUI
coollabsio/coolify pull request #4444
Opened 2024-11-30 00:23 UTC by elmatadoor

## Changes
Add [Matrix](https://matrix.org/) Chat as Service With [Element ](https://element.io/) WebUI 
The matrix.org server is working, but the homeserver needs proper setup in the homeserver.yaml file.

2024-12-02 11:57 UTC, peaklabs-dev commented
This template is not yet completed I think because there is no port and no way to access the service over a domain is this intended? Please use the Coolify Magic to make this work: https://coolify.io/docs/knowledge-base/docker/compose#coolifys-magic-environment-variables

2024-12-02 18:31 UTC, elmatadoor commented
> Thanks it looks better now as you said the healthchecks are missing and not sure what you mean by homeserver.yaml but these steps should be automated if possible inside the compose file or if not possible via docs.

matrix.org is a decentralised communication platforme ; you can create an account on the main network called [matrix.org] or you can be the owner of the data by editing the homeserver.yaml  to save all app data in your local server
take a look here 
https://prnt.sc/vK-rEHf6ko3M
https://prnt.sc/Vqt-PULMTH9B

2024-12-03 16:43 UTC, peaklabs-dev requested changes
Please make the changes in my comments and also add healthchecks to each container.

2024-12-03 16:43 UTC, peaklabs-dev commented on templates/compose/matrix-element.yml
> +    restart: unless-stopped
not needed coolify adds this by default.

2024-12-03 16:43 UTC, peaklabs-dev commented on templates/compose/matrix-element.yml
> +# logo: svgs/matrix-element.svg
Add Port for the service

2024-12-03 16:43 UTC, peaklabs-dev commented on templates/compose/matrix-element.yml
> +      - synapse_db
Make sure the health checks check for condition healthy of the resource.

2024-12-03 16:43 UTC, peaklabs-dev commented on templates/compose/matrix-element.yml
> +volumes:
Remove this as Coolify will autogenerate this

2024-12-03 19:10 UTC, elmatadoor commented
@peaklabs-dev could you please guide me with code snippets ; Add Port for the service &  health checks

2024-12-07 06:01 UTC, luckydonald commented
How would one supply a entrypoint script?
Entry in `volumes:` with `content` set to something?

2024-12-07 21:52 UTC, elmatadoor commented
> How would one supply a entrypoint script? Entry in `volumes:` with `content` set to something?

what do ypu mean bro ?

2024-12-08 02:49 UTC, luckydonald commented
This is in reply to @peaklabs-dev's [comment](https://github.com/coollabsio/coolify/pull/4444#issuecomment-2517162851).
And what I mean is this: https://coolify.io/docs/knowledge-base/docker/compose#create-a-file-with-content

2024-12-10 21:34 UTC, elmatadoor commented
we have add somme editing and the entrypoint as well to generate the config file  ; it is working on coolify but for somme reason generating config file on the fly is not working ; i generate it manualy by running the command i just montion in top comment here is the oficiel docker image with guides : [DOCKER HUB](https://hub.docker.com/r/matrixdotorg/synapse)

2024-12-21 22:34 UTC, elmatadoor commented
Run The Following Command To Generate The : homeserver.yaml in [/var/lib/docker/volumes/synapse_data/_data] : 
docker run --rm -e SYNAPSE_SERVER_NAME=element-b48owg0cwsg0cssoksosw88c.yourdomain -e SYNAPSE_REPORT_STATS=no -v /var/lib/docker/volumes/b48owg0cwsg0cssoksosw88c_synapse-data/_data:/data matrixdotorg/synapse:v1.84.1 generate
edit the [homeserver.yaml] located at [/var/lib/docker/volumes/synapse_data/_data] to enable registration to your homeserver by adding this 2 lines at the end of the file : 
enable_registration: true
enable_registration_without_verification: true
if any one can test it and help use make this PR in Production

2025-01-06 11:21 UTC, peaklabs-dev requested changes
Please also add healthchecks to element, coturn and postgres (the db)

2025-01-06 11:21 UTC, peaklabs-dev commented on templates/compose/matrix.yaml
> +    container_name: synapse
remove container name

2025-01-06 11:21 UTC, peaklabs-dev commented on templates/compose/matrix.yaml
> +      - SERVICE_FQDN_MATRIX=${SERVICE_FQDN_MATRIX}
this line should just be -SERVICE_FQDN_MATRIX

2025-01-06 11:21 UTC, peaklabs-dev commented on templates/compose/matrix.yaml
> +      - synapse_db
Add healthy check here:
```yaml
depends_on:
      synapse_db:
        condition: service_healthy
```

2025-01-07 17:52 UTC, elmatadoor commented on templates/compose/matrix.yaml
> +      - synapse_db
Editing done 
what else should i fix

2025-01-09 14:37 UTC, peaklabs-dev commented on templates/compose/matrix.yaml
> +      - synapse_db
Now each container just needs a `depends_on:` and a `healthcheck:` section with working healthcheks so it all starts up properly.

2025-01-09 15:02 UTC, elmatadoor commented on templates/compose/matrix.yaml
> +      - synapse_db
Please send me a pastbin file on how it should look like and i will do it

2025-01-14 11:42 UTC, peaklabs-dev commented on templates/compose/matrix.yaml
> +      - synapse_db
You can check this for an example healthcheck: https://github.com/coollabsio/coolify/blob/676f616efa668e92e3adda7c87cdea685f1000a5/templates/compose/nextcloud-with-postgres.yaml#L43-L47

2025-01-22 16:38 UTC, closed without merging

2025-01-22 16:38 UTC, peaklabs-dev commented
Thank you for your contribution. Due to inactivity, we're closing this PR. If you'd like to revisit this change, feel free to reopen this PR or open a new pull request.

2025-01-23 22:36 UTC, adaichendt-tv1 commented
Hey, I picked this up but am stuck now. It seems like coolify is not expanding the variables USER_POSTGRESQL and PASSWORD_POSTGRESQL in the /data/homeserver.yaml file content definition despite the docs saying it should work like this. 

I am on beta 389.

```
# Documentation: https://github.com/kamyargerami/matrix-docker
# Slogan: An open network for secure, decentralised communication
# Tags: real-time-messaging, secure-communication, peer-to-peer
# Logo: svgs/matrix-element.svg
# Port: 80

services:

  synapse:
    image: "docker.io/matrixdotorg/synapse:v1.84.1"
    environment:
      - SERVICE_FQDN_MATRIX=${SERVICE_FQDN_MATRIX}
      - USER_POSTGRESQL=${SERVICE_USER_POSTGRESQL}
      - PASSWORD_POSTGRESQL=${SERVICE_PASSWORD_POSTGRESQL}
    volumes:
      - synapse_data:/data
      - type: bind
        source: ./data/log.config
        target: /data/log.config
        content: |
            version: 1

            formatters:
                precise:
                    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

            handlers:
                file:
                    class: logging.handlers.TimedRotatingFileHandler
                    formatter: precise
                    filename: /data/homeserver.log
                    when: midnight
                    backupCount: 3  # Does not include the current log file.
                    encoding: utf8

                # Default to buffering writes to log file for efficiency.
                # WARNING/ERROR logs will still be flushed immediately, but there will be a
                # delay (of up to `period` seconds, or until the buffer is full with
                # `capacity` messages) before INFO/DEBUG logs get written.
                buffer:
                    class: synapse.logging.handlers.PeriodicallyFlushingMemoryHandler
                    target: file

                    # The capacity is the maximum number of log lines that are buffered
                    # before being written to disk. Increasing this will lead to better
                    # performance, at the expensive of it taking longer for log lines to
                    # be written to disk.
                    # This parameter is required.
                    capacity: 10

                    # Logs with a level at or above the flush level will cause the buffer to
                    # be flushed immediately.
                    # Default value: 40 (ERROR)
                    # Other values: 50 (CRITICAL), 30 (WARNING), 20 (INFO), 10 (DEBUG)
                    flushLevel: 30  # Flush immediately for WARNING logs and higher

                    # The period of time, in seconds, between forced flushes.
                    # Messages will not be delayed for longer than this time.
                    # Default value: 5 seconds
                    period: 5

                # A handler that writes logs to stderr. Unused by default, but can be used
                # instead of "buffer" and "file" in the logger handlers.
                console:
                    class: logging.StreamHandler
                    formatter: precise

            loggers:
                synapse.storage.SQL:
                    # beware: increasing this to DEBUG will make synapse log sensitive
                    # information such as access tokens.
                    level: INFO

            root:
                level: INFO

                # Write logs to the `buffer` handler, which will buffer them together in memory,
                # then write them to a file.
                #
                # Replace "buffer" with "console" to log to stderr instead.
                #
                handlers: [buffer]

            disable_existing_loggers: false

      - type: bind
        source: ./data/homeserver.yaml
        target: /data/homeserver.yaml
        mode: "0755"
        content: |
            database:
                name: psycopg2
                args:
                    user: $USER_POSTGRESQL
                    password: $PASSWORD_POSTGRESQL
                    database: synapse
                    host: synapse_db
                    cp_min: 5
                    cp_max: 10

            server_name: "SERVERNAME"
            pid_file: /data/homeserver.pid
            listeners:
              - port: 8008
                tls: false
                type: http
                x_forwarded: true
                bind_addresses: ['::1', '127.0.0.1']
                resources:
                - names: [client, federation]
                  compress: false
            log_config: "/data/log.config"
            media_store_path: /data/media_store
            signing_key_path: "/data/signing.key"
            trusted_key_servers:
            - server_name: "matrix.org"
            report_stats: false

    entrypoint: |
        sh -c "chown 991:991 /data/homeserver.yaml &&
        python -m synapse.app.homeserver --config-path /data/homeserver.yaml"
    depends_on:
      synapse_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15

  synapse_db:
    image: "docker.io/postgres:14-alpine"
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRESQL}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}
    volumes:
      - synapse_db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
        interval: 5s
        timeout: 20s
        retries: 10

  coturn:
    image: "instrumentisto/coturn:latest"
    volumes:
      - coturn:/etc/coturn
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3478 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  element:
    image: "vectorim/element-web:latest"
    volumes:
      - element:/app
    environment:
      - SERVICE_FQDN_ELEMENT=${SERVICE_FQDN_ELEMENT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 10s
      retries: 5
```