Harden Vaultwarden installation
coollabsio/coolify pull request #4446
Opened 2024-11-30 08:18 UTC by Virviil

## Submit Checklist (REMOVE THIS SECTION BEFORE SUBMITTING)
- [ ] I have selected the `next` branch as the destination for my PR, not `main`.
- [ ] I have listed all changes in the `Changes` section.
- [ ] I have filled out the `Issues` section with the issue/discussion link(s) (if applicable).
- [ ] I have tested my changes.
- [ ] I have considered backwards compatibility.
- [ ] I have removed this checklist and any unused sections.

## Changes
- Make Vaultwarden installation to use Postgres as storage, that allows to perform backups using standard Coolify mechanisms.
- Changing logo from licensed Bitwarden to Vaultwarden

## Issues
- fix #

2024-11-30 08:21 UTC, Virviil commented
I don't understand how `templates/service-templates.json` file is created, but I hope that automatically.
It's probably should be changed before merging this PR.

@peaklabs-dev hope you can point me out

2024-11-30 13:00 UTC, peaklabs-dev commented
The json will be generated by use for now. It is great that you did not commit it to the PR as that could cause problems. You van test your changes using the docker compose empty deploy type.

2024-11-30 13:53 UTC, Virviil commented
@peaklabs-dev I've checked it as docker-compose deployment - all is working (as expected for this setup)

2024-12-02 11:54 UTC, peaklabs-dev requested changes
Since the postgres version is like a new version of vaultwarden, add a `vaultwarden-postgres.yaml` file and leave the old one as it is. 

Also, I have tested it and it does not work for me, so please go through the new template and test it thoroughly.

2024-12-02 11:54 UTC, peaklabs-dev commented on templates/compose/vaultwarden.yaml
> +    image: postgres:alpine
Please use a version number such as 16 or so.

2024-12-02 11:54 UTC, peaklabs-dev commented on templates/compose/vaultwarden.yaml
> -      - IP_HEADER=X-Forwarded-For
Keep this variable as it is needed to get the right IPs

2024-12-16 11:29 UTC, peaklabs-dev commented
Thank you for your contribution. Due to inactivity, we're closing this PR. If you'd like to revisit this change, feel free to reopen this PR or open a new pull request.

2024-12-16 11:29 UTC, closed without merging